# Test file for API HTTP routes

@endpoint = http://localhost:{{$dotenv PORT}}

### 404
GET {{ endpoint }}/somethingsmart

############################
#         ARTWORKS         #
############################

### List of all artworks
GET {{ endpoint }}/artworks

### Get one artwork based on its id
GET {{ endpoint }}/artworks/6

############################
#         ROLES        #
############################

### List of all roles
GET {{ endpoint }}/roles

### Get one role based on its id
GET {{ endpoint }}/roles/3

############################
#         USERS         #
############################

### List of all users
GET {{ endpoint }}/users

### Get one user based on its id
GET {{ endpoint }}/users/2

### Get one user based on its pseudo
GET {{ endpoint }}/users/mezange