# Test file for API HTTP routes

@endpoint = http://localhost:{{$dotenv PORT}}

### 404
GET {{ endpoint }}/somethingsmart

############################
#         ARTWORKS         #
############################

### List of all artworks
GET {{ endpoint }}/artworks

### List of all artworks from a user
GET {{ endpoint }}/artworks/user/4

### Get one artwork based on its id
GET {{ endpoint }}/artworks/6

### Create a new artwork in database if does not already exist
POST {{ endpoint }}/artworks
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiZW1haWwiOiJlbWVyaWMubG95ZXJAZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTAkZzVXcU5nWHozVDY2TVFETFF4anZUZU5ldVFhZmdsRm16eDYuTExwVExWUlFKMURUc2ZzanEiLCJwc2V1ZG8iOiJNZXphbmdlIiwiY291bnRyeSI6IkZyYW5jZSIsImRlc2NyaXB0aW9uIjoiTkZUIGNyZWF0b3IiLCJwcm9maWxlX3BpYyI6bnVsbCwiY3JlYXRlZF9hdCI6IjIwMjItMTItMTVUMTU6MTE6MzkuMjE0WiIsInVwZGF0ZWRfYXQiOm51bGwsInJvbGVfaWQiOjMsImlwIjoiOjpmZmZmOjEyNy4wLjAuMSIsImlhdCI6MTY3MTE4NDg3MiwiZXhwIjoxNjcxMjA2NDcyfQ.ebddNYWnsEf8PcaZ0JM3Utj1rHdWVdoe2mOKmPU-R_s

{
    "name": "TestArtwork",
    "image": "imagefile",
    "description": "Lorem ipsum",
    "artist_name": "Artist",
    "price_usd": 999,
    "price_sol": 450
}

### Update an artwork data in database
PATCH {{ endpoint }}/artworks/7
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiZW1haWwiOiJlbWVyaWMubG95ZXJAZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTAkZzVXcU5nWHozVDY2TVFETFF4anZUZU5ldVFhZmdsRm16eDYuTExwVExWUlFKMURUc2ZzanEiLCJwc2V1ZG8iOiJNZXphbmdlIiwiY291bnRyeSI6IkZyYW5jZSIsImRlc2NyaXB0aW9uIjoiTkZUIGNyZWF0b3IiLCJwcm9maWxlX3BpYyI6bnVsbCwiY3JlYXRlZF9hdCI6IjIwMjItMTItMTVUMTU6MTE6MzkuMjE0WiIsInVwZGF0ZWRfYXQiOm51bGwsInJvbGVfaWQiOjMsImlwIjoiOjpmZmZmOjEyNy4wLjAuMSIsImlhdCI6MTY3MTE4NDg3MiwiZXhwIjoxNjcxMjA2NDcyfQ.ebddNYWnsEf8PcaZ0JM3Utj1rHdWVdoe2mOKmPU-R_s

{
    "description": "Lorem ipsum",
    "price_usd": 500,
    "price_sol": 500
}

### Delete an artwork data in database
DELETE {{ endpoint }}/artworks/6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiZW1haWwiOiJlbWVyaWMubG95ZXJAZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTAkZzVXcU5nWHozVDY2TVFETFF4anZUZU5ldVFhZmdsRm16eDYuTExwVExWUlFKMURUc2ZzanEiLCJwc2V1ZG8iOiJNZXphbmdlIiwiY291bnRyeSI6IkZyYW5jZSIsImRlc2NyaXB0aW9uIjoiTkZUIGNyZWF0b3IiLCJwcm9maWxlX3BpYyI6bnVsbCwiY3JlYXRlZF9hdCI6IjIwMjItMTItMTVUMTU6MTE6MzkuMjE0WiIsInVwZGF0ZWRfYXQiOm51bGwsInJvbGVfaWQiOjMsImlwIjoiOjpmZmZmOjEyNy4wLjAuMSIsImlhdCI6MTY3MTE4NDg3MiwiZXhwIjoxNjcxMjA2NDcyfQ.ebddNYWnsEf8PcaZ0JM3Utj1rHdWVdoe2mOKmPU-R_s

############################
#       LOGIN/LOGOUT       #
############################

### User login
POST {{ endpoint }}/users/login
content-type: application/json

{
    "pseudo": "Mezange",
    "password": "NFT"
}

### User logout
POST {{ endpoint }}/users/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiZW1haWwiOiJlbWVyaWMubG95ZXJAZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTAkb0JrYTRpbjVmenBWOHRmb2RlaUtqLk5SdWdrbzBCLlQzUlROUUJMcHQySmZPaTN6WE9FanUiLCJwc2V1ZG8iOiJNZXphbmdlIiwiY291bnRyeSI6IkZyYW5jZSIsInByb2ZpbGVfcGljIjpudWxsLCJjcmVhdGVkX2F0IjoiMjAyMi0xMi0xM1QxNDowNzoyNy4wNDNaIiwidXBkYXRlZF9hdCI6bnVsbCwicm9sZV9pZCI6MywiaXAiOiI6OmZmZmY6MTI3LjAuMC4xIiwiaWF0IjoxNjcxMDExNTgwLCJleHAiOjE2NzEwMzMxODB9.rRIeoDjDzDaJHfWl15Zj7Mr9ioz96spGj9nvam_imN4

### Invalid User login - Unauthorized
POST {{ endpoint }}/users/login
content-type: application/json

{
    "pseudo": "pseudo",
    "password": "secretpassword"
}

### Invalid User login - Bad request
POST {{ endpoint }}/users/login
content-type: application/json

{
    "pseudo": "Mezange"
}

############################
#         ROLES            #
############################

### List of all roles
GET {{ endpoint }}/roles

### Get one role based on its id
GET {{ endpoint }}/roles/3

############################
#      SIGNUP/SIGNOUT      #
############################

### Create a new user in database if does not already exist
POST {{ endpoint }}/users/signup
content-type: application/json

{
    "email": "test@test.com",
    "password": "secretpassword",
    "country": "France",
    "pseudo": "pseudo"
}

### Invalid create user request
POST {{ endpoint }}/users/signup
content-type: application/json

{
    "email": "eergergerg",
    "password": "secretpassword"
}

### Delete a user in database if exists
DELETE {{ endpoint }}/users/signout/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiZW1haWwiOiJlbWVyaWMubG95ZXJAZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTAkTi42dXRiTGttdjNlQ3IxL2VHT0cvLjExdHJ0ODZjeGlDZ0JNYjd3TDB2VWUxLnVqbFV0eFMiLCJwc2V1ZG8iOiJNZXphbmdlIiwiY291bnRyeSI6IkZyYW5jZSIsImRlc2NyaXB0aW9uIjoiTkZUIGNyZWF0b3IiLCJwcm9maWxlX3BpYyI6bnVsbCwiY3JlYXRlZF9hdCI6IjIwMjItMTItMTZUMTY6MDU6NDAuODI2WiIsInVwZGF0ZWRfYXQiOm51bGwsInJvbGVfaWQiOjMsImlwIjoiOjpmZmZmOjEyNy4wLjAuMSIsImlhdCI6MTY3MTIwNjc4OCwiZXhwIjoxNjcxMjI4Mzg4fQ.uXr5ZNeRghVDJMH4EdIIC4IJefQySWCujyZin1Tx87U

############################
#         USERS            #
############################

### List of all users
GET {{ endpoint }}/users
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiZW1haWwiOiJlbWVyaWMubG95ZXJAZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTAkb0JrYTRpbjVmenBWOHRmb2RlaUtqLk5SdWdrbzBCLlQzUlROUUJMcHQySmZPaTN6WE9FanUiLCJwc2V1ZG8iOiJNZXphbmdlIiwiY291bnRyeSI6IkZyYW5jZSIsInByb2ZpbGVfcGljIjpudWxsLCJjcmVhdGVkX2F0IjoiMjAyMi0xMi0xM1QxNDowNzoyNy4wNDNaIiwidXBkYXRlZF9hdCI6bnVsbCwicm9sZV9pZCI6MywiaXAiOiI6OmZmZmY6MTI3LjAuMC4xIiwiaWF0IjoxNjcxMDExNTgwLCJleHAiOjE2NzEwMzMxODB9.rRIeoDjDzDaJHfWl15Zj7Mr9ioz96spGj9nvam_imN4

### Get one user based on its id
GET {{ endpoint }}/users/2

### Get one user based on its pseudo
GET {{ endpoint }}/users/mezange
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiZW1haWwiOiJlbWVyaWMubG95ZXJAZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTAkb0JrYTRpbjVmenBWOHRmb2RlaUtqLk5SdWdrbzBCLlQzUlROUUJMcHQySmZPaTN6WE9FanUiLCJwc2V1ZG8iOiJNZXphbmdlIiwiY291bnRyeSI6IkZyYW5jZSIsInByb2ZpbGVfcGljIjpudWxsLCJjcmVhdGVkX2F0IjoiMjAyMi0xMi0xM1QxNDowNzoyNy4wNDNaIiwidXBkYXRlZF9hdCI6bnVsbCwicm9sZV9pZCI6MywiaXAiOiI6OmZmZmY6MTI3LjAuMC4xIiwiaWF0IjoxNjcxMDExNTgwLCJleHAiOjE2NzEwMzMxODB9.rRIeoDjDzDaJHfWl15Zj7Mr9ioz96spGj9nvam_imN4

### Update one user data in database
PATCH {{ endpoint }}/users/4
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiZW1haWwiOiJlbWVyaWMubG95ZXJAZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTAkWU8wdGI2RkRDTHBkR3JhTE1yRWlPZThsYmR2OEc0YjV1MlNRQTBGNVB6dC5TMXYuM3UzeEciLCJwc2V1ZG8iOiJNZXphbmdlIiwiY291bnRyeSI6IkZyYW5jZSIsImRlc2NyaXB0aW9uIjoiTkZUIGNyZWF0b3IiLCJwcm9maWxlX3BpYyI6bnVsbCwiY3JlYXRlZF9hdCI6IjIwMjItMTItMTVUMDg6MjI6NDMuNDk4WiIsInVwZGF0ZWRfYXQiOm51bGwsInJvbGVfaWQiOjMsImlwIjoiOjpmZmZmOjEyNy4wLjAuMSIsImlhdCI6MTY3MTExNTY3MSwiZXhwIjoxNjcxMTM3MjcxfQ.H3kES8i8qTwSKbehZSa6YIV1K4Admh-Rp8ZLHUtRVfI

{
    "description": "Que vienne la nuit sonne l'heure"
}